# Site settings
title: Infernus
email: james+www@infernus.org
description: > # this means to ignore newlines until "baseurl:"
  Egotistical ramblings that won't fit in 140 characters.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jshiell.github.io" # the base hostname & protocol for your site
twitter_username: jshiell
github_username:  jshiell

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
encoding: utf-8
